optional rcs, --list and --interactive modes
- add --list option to list available files
- add --interactive mode to ask about every file
- put optional files in rcs/optional/

diff --git a/make-shellrc b/make-shellrc
--- a/make-shellrc
+++ b/make-shellrc
@@ -1,15 +1,7 @@
 #!/bin/bash
-
-# TODO:
-# [x] determine shell
-# [x] find existing .[zsh|bash]rc
-# [x] --shellrc
-# [x] iterate through parts of file, include if not included
-# [x] add usage
-# [ ] figure out how to run remotely (seperate repo?)
-# [ ] iterate through .zsh / .bash only files
-# [ ] add --include and --exclude flags
-# [ ] add sed to check "mksh: check for"
+#
+# make-shellrc -- generate startup file for your shell
+#
 
 set -Eeo pipefail # fail on errors, even within pipes
 rootdir=$(cd "${0%/*}/." && pwd -P)
@@ -40,8 +32,10 @@ usage() {
 
   OPTIONS
 
-  --shellrc [FILE]      Where to write the file
-  --shell [SHELL]       Shell to generate the file for (bash, zsh)
+  -r|--rc [FILE]        Where to write the file
+  -s|--shell [SHELL]    Shell to generate the file for (bash, zsh)
+  -l|--list             List available rc files to include
+  -i|--interactive      Ask about all files to include. (default is to only prompt if optional)
   -v, --verbose         Verbose mode
   -n, --dry-run         Do not make changes, just preview them
   -h, --help            Show this help information
@@ -99,8 +93,18 @@ is_dry_run() {
 }
 
 # succeeds if in verbose mode
+is_always_ask() {
+  [ -n "${always_ask}" ]
+}
+
+# succeeds if in verbose mode
 is_verbose() {
   [ -n "${verbose_mode}" ]
+}
+
+# succeeds if in verbose mode
+is_list() {
+  [ -n "${list_mode}" ]
 }
 
 # backup $shellrc to $backup_file
@@ -117,11 +121,13 @@ args() {
   local sn=1
 
   while [ $# -gt 0 ]; do case $1 in
-      --shellrc)    sn=2 shellrc="$2"            ;;
-      --shell)      sn=2 shell="$2"              ;;
-      -n|--dry-run) sn=1 dry_run_mode=true       ;;
-      -v|--verbose) sn=1 verbose_mode=true       ;;
-      -h|--help)    usage ; exit                 ;;
+      -r|--rc)           sn=2 shellrc="$2"            ;;
+      -s|--shell)        sn=2 shell="$2"              ;;
+      -l|--list)         sn=1 list_mode=true          ;;
+      -i|--interactive)  sn=1 always_ask=true         ;;
+      -n|--dry-run)      sn=1 dry_run_mode=true       ;;
+      -v|--verbose)      sn=1 verbose_mode=true       ;;
+      -h|--help)         usage ; exit                 ;;
       *) : ;;
     esac
     shift $sn
@@ -140,7 +146,7 @@ find_shell() {
     shell=${SHELL##*/}
   fi
 
-  [ -z "${shell}" ] && abort "Unable to determine shell. Please specify with --shell or --shellrc."
+  [ -z "${shell}" ] && abort "Unable to determine shell. Please specify with --shell or --rc."
 
   if ! [[ "${shell}" =~ ^(bash|zsh)$ ]]; then
     abort "Unsupported shell: '${shell}'. (If this seems like a mistake, specify with --shell.)"
@@ -165,12 +171,14 @@ rcs_to_add() {
     '/^# mksh: check for / s///p' \
   )
 
-  for rc_file in "${rootdir}/rcs"/*.sh "${rootdir}/rcs"/*."${shell}"; do
+  # iterate through the list of all files
+  for rc_file in "${rootdir}/rcs"/*.sh "${rootdir}/rcs/optional"/*."${shell}" "${rootdir}/rcs/optional"/*.sh; do
 
-    info "Including: ${rc_file##*/}"
 
     add_file=true
 
+    # get content from this file based on "# mksh:" comments
+    # exclude this file if that content is already in the users shellrc
     for script in "${scripts[@]}"; do
       if read -r pat < <(sed -nEe "${script}" "${rc_file}"); then
         if grep -q "${pat}" "${shellrc}"; then
@@ -180,19 +188,97 @@ rcs_to_add() {
     done
 
     if [[ "${add_file}" == "true" ]]; then
+
+      # add to the *_rclist arrays
+      if [[ "${rc_file}" =~ optional ]]; then
+        opt_rclist+=( "${rc_file}" )
+      else
+        req_rclist+=( "${rc_file}" )
+      fi
+
+      # add to files array
       files+=( "${rc_file}" )
     fi
 
   done
+}
 
-  prompt || exit
+# succeeds if the filepath has "optional" in it
+is_optional() {
+  [[ "${1}" =~ optional ]]
+}
+
+# print the name and description of one file
+file_info() {
+  local file="${1}" length="${2:-10}" newline="\n" symbol="-" name desc
+
+  if is_optional "${file}"; then
+    symbol="*"
+  fi
+
+  name="${file##*/}"
+  desc="$(grep -B1 '^# -*$' "${file}" | sed -Ee '$d ; s/# //; s/^.* -- //')"
+
+  printf "%s %-*s : %-*s" "${symbol}" $length "${name}" 45 "${desc}"
+
+  if ! [[ "${*}" =~ "-n" ]]; then
+    echo
+  fi
+}
+
+# interactively as which files should be included
+# for all files if is_always_ask, otherwise just the optional ones
+# append files to chosen array
+interactive() {
+  local maxlen=0 file name nl=""
+
+  # get the max length of the filename
+  for file in "${files[@]}"; do
+    name="${file##*/}"
+    if [[ ${#name} -gt $maxlen ]]; then
+      maxlen=${#name}
+    fi
+  done
+
+  for file in "${files[@]}"; do
+    if is_always_ask || is_optional "${file}" ; then
+      nl="-n"
+    else
+      nl=""
+    fi
+
+    file_info "$file" $maxlen $nl
+
+    if is_always_ask || is_optional "${file}"; then
+      prompt " Add?" || continue
+      chosen+=( "${file}" )
+    fi
+  done
+}
+
+# print list of required and optional files
+file_list() {
+  local file
+
+  for file in "${files[@]}"; do
+    file_info "$file"
+  done
+}
+
+# print list of required and optional files
+list() {
+  printf "\n\033[1mRC Files\033[0m\n\n"
+
+  file_list | column -t -s':'
+
+  printf "\n\n( - recommended,  * optional )\n\n"
 }
 
 # generate a shellrc file
 generate() {
   local file
 
-  for file in "${shellrc}" "${files[@]}"; do
+  for file in "${shellrc}" "${@}"; do
     sed -Ee '/# mksh: check if present/ s/// ; /^# mksh: check for /d' "${file}"
   done
 }
@@ -213,7 +299,7 @@ preview() {
   printf "\033[1m%s Preview\033[0m\n" "${shellrc##*/}"
   printf "\033[32m-----------------------------------------------------------------------\033[0m\n\n"
 
-  generate
+  generate "${chosen[@]}"
 
   printf "\033[32m=======================================================================\033[0m\n\n"
 }
@@ -233,7 +319,7 @@ save() {
 
 main() {
   local shellrc shell backup_file timestamp args
-  local -a files
+  local -a files chosen
 
   args ${1:+"$@"}
   find_shell
@@ -246,10 +332,16 @@ main() {
 
   show_var shell shellrc backup_file args
 
-  prompt || return
+  # prompt || return
 
   rcs_to_add
 
+  if is_list; then
+    list
+    return
+  fi
+
+  interactive
   preview | ${PAGER:-less}
   save
 }
